### ISSUE TITLE
您好，方便留个QQ给我吗？有些问题想请教你

### ISSUE THREAD

**Issue by edisonleeeeee** [LeeWongSnail/ArtScrollTableView#1]
如题！！！谢谢！！

**Comment by LeeWongSnail** [comment]
直接在这里提问就好了 方便大家分享问题

**Comment by DamonRao** [comment]
tablecell下面的怎么添加多个不同的控制器

**Comment by LeeWongSnail** [comment]
这里 我是在cell中放了一个控制器，而这个控制器又是一个多控制器管理。我这里使用的是UIPageViewController，如果想添加的多个控制器是不同的控制器 可以在这里

```
[self.workFilterModel setContentViewController:^UIViewController *(NSDictionary *info) {
    ArtSubTableViewController *controller = [[ArtSubTableViewController alloc] init];
    controller.view.backgroundColor = [UIColor colorWithRed:arc4random_uniform(255)/255. green:arc4random_uniform(255)/255. blue:arc4random_uniform(255)/255. alpha:1.];
    return controller;
}];
```

根据每个分类的info的不同提供不同的控制器。这样就可以实现多个不同的控制器了。

**Comment by DamonRao** [comment]
不太明白最后一句，从哪里改不同info加不同控制器

**Comment by LeeWongSnail** [comment]
@DamonRao  
ArtWorkFilterModel 的init方法中有这么一个设置 这个设置是因为我当时写死了 所以写到里面去了，你可以在外面给这个ArtWorkFilterModel 设置categoryList 属性 到时候 我上面所说的info就是这里你提供的每个分类对一个的字典 你可以根据id的不同来设置不同的控制器。

```
self.categoryList = @[@{@"name":@"关注",@"_id":@"1"}, @{@"name":@"热门",@"_id":@"2"}, @{@"name":@"最新",@"_id":@"3"}];
```

demo写的有点混乱，有时间 我修改一下 你先将就看一下

**Comment by DamonRao** [comment]
哦哦，好的，3Q

**Comment by LeeWongSnail** [comment]
@DamonRao  OK

**Comment by DamonRao** [comment]
楼主搞了半天，还是不会添加啊

**Comment by LeeWongSnail** [comment]
@DamonRao demo中我稍微改了一下 下面的三个控制器 我换了一个 你看一下 我问题在问我哈

**Comment by DamonRao** [comment]
这段有问题，没返回值，放在if里面没用
 if ([info[@"_id"] isEqualToString:@"2"]){
             ArtSubTableViewController *controller1 = [[ArtSubTableViewController alloc] init];
             return controller1;
         }

**Comment by LeeWongSnail** [comment]
@DamonRao  可否描述的清晰一点 哪里没有返回值 放到if里没用？

**Comment by DamonRao** [comment]
添加控制器这里
    //    WEAKSELF(weakSelf);
    //这里的info对应的为上面设置的workFilterModel中的categorylist
    [self.workFilterModel setContentViewController:^UIViewController *(NSDictionary *info) {
        if ([info[@"_id"] isEqualToString:@"2"]) {
            ArtThirdViewController *third = [[ArtThirdViewController alloc] init];
            return third;
        } else {
            ArtSubTableViewController *controller = [[ArtSubTableViewController alloc] init];
            controller.view.backgroundColor = [UIColor colorWithRed:arc4random_uniform(255)/255. green:arc4random_uniform(255)/255. blue:arc4random_uniform(255)/255. alpha:1.];
            return controller;
        }
    }];

**Comment by LeeWongSnail** [comment]
两种情况都设置了返回值啊，你是说info有问题吗?

**Comment by DamonRao** [comment]
没有问题了，刚是我自己先前改的东西有一个没删掉😓

**Comment by LeeWongSnail** [comment]
@DamonRao  没有问题就好。

**Comment by DamonRao** [comment]
再打扰一下吗，我想今天把那个这个功能集成到我自己的项目中，结果置顶以后就没办法拉下来了
#pragma mark - UISCrollviewDelegate

-(void)scrollViewDidScroll:(UIScrollView *)scrollView{
    CGFloat tabOffsetY = [_tableView rectForSection:2].origin.y;
    CGFloat offsetY = scrollView.contentOffset.y;
    NSLog(@"offsetY ----- %f",offsetY);
    NSLog(@"tabOffsetY ----- %f",tabOffsetY);
    _isTopIsCanNotMoveTabViewPre = _isTopIsCanNotMoveTabView;

```
if (offsetY>=tabOffsetY) {
    scrollView.contentOffset = CGPointMake(0, tabOffsetY);
    _isTopIsCanNotMoveTabView = YES;
}else{
    _isTopIsCanNotMoveTabView = NO;
}
```

这一块的offsetY的初始值是怎么计算的啊

**Comment by LeeWongSnail** [comment]
如果你要集成的话 只要看一下 你的
CGFloat tabOffsetY = [_tableView rectForSection:2].origin.y;  tableview有几个scetion 具体的位置
其他的内容都是我自己监听的 应该不需要你做改动，顺便看一下 的tableview是否为group类型

**Comment by DamonRao** [comment]
tableOffsetY的位置是没错的前面有几个section相应排下来就有多少距离，主要是我的offsetY初始值是0，而你的demo中初始值是－64我有点不明白

**Comment by LeeWongSnail** [comment]
64是导航栏的高度吧 你在仔细看一下

**Comment by DamonRao** [comment]
应该不是吧，你这个表格不是设置高度是self.view 么

**Comment by LeeWongSnail** [comment]
如果设置了导航栏scrollview的初始的contentoffset的确是从-64开始的(这个你可以写个demo验证一下)，如果你的初始的offset为0的话可能是你设置了控制器的这个属性吧 （automaticallyAdjustsScrollViewInsets）

**Comment by DamonRao** [comment]
-64时状态栏和导航栏的高度，但是我的offsetY初始值没有产生移位啊，所以我讲tableOffsetY的值就没有减64，改成以下代码，可是就完全table不能上拉置顶了
-(void)scrollViewDidScroll:(UIScrollView *)scrollView{
    CGFloat tabOffsetY = [_tableView rectForSection:2].origin.y;
    CGFloat offsetY = scrollView.contentOffset.y;
    NSLog(@"offsetY ----- %f",offsetY);
    NSLog(@"tabOffsetY ----- %f",tabOffsetY);

**Comment by LeeWongSnail** [comment]
请问你们的代码是用什么做的布局呢 Masonry还是 计算frame呢

**Comment by DamonRao** [comment]
混合的，不过我刚刚好像解决了主要是因为self.view的位置问题我这边没用把导航的位置算进来，因为你方法力监听是整个屏幕的，我改了CGFloat offsetY = scrollView.contentOffset.y－64;其他的都不要减什么位移量就可以了，主要还是导航跳转后位置偏移对scrollview的contentoffset的变化，总之谢谢啦

**Comment by DamonRao** [comment]
不过我有点奇怪的是，我没使用（automaticallyAdjustsScrollViewInsets）方法，怎么scrollView.contentOffset.y的偏移量为零呢，一般不都应该是会偏移个64吗

**Comment by LeeWongSnail** [comment]
是的呢 我单独写过一个东西试了一下 我这边的确都是64  应该还是有哪些地方影响了 你可以根据你的思路去试一下。

**Comment by DamonRao** [comment]
我点进入页面退出后又点击进入却又报错了：erminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Signal <RACDynamicSignal: 0x7fc52ba26da0> name:  is already bound to key path "categoryListIndex" on object <ArtWorkFilterModel: 0x7fc52975e7b0>, adding signal <RACDynamicSignal: 0x7fc52baa35b0> name:  is undefined behavior'

这个应该是你artsubcell用到的reactive cocoa库里的东西报错了,是什么原因呢

**Comment by LeeWongSnail** [comment]
```
RAC(self.workFilterModel, categoryListIndex) = [RACObserve(self.scrollTab, currentIndex) takeUntil:[self rac_signalForSelector:@selector(viewWillDisappear:)]];
```

改成这个试一下

**Comment by DamonRao** [comment]
可以了，可是还有个疑问是：前面的两行不能选中啊，绿色banner上面的几行

**Comment by LeeWongSnail** [comment]
可以选中的啊  我没加点击的代理方法 或者说我没理解清除

**Comment by DamonRao** [comment]
可以的，我刚用了个跳转页面试了一下；之前觉得不可以是我直接模拟器运行时点击没有出点击阴影，我的锅，没有仔细试一下太仓促就直接问你，我刚学ios不就有点菜，嘿嘿

**Comment by LeeWongSnail** [comment]
没关系 一起学习

**Comment by DamonRao** [comment]
还有个问题想跟你探讨一下，绿色bannner下各个分控制器里的表格的单元格点击响应事件问题怎么去实现啊

**Comment by LeeWongSnail** [comment]
就是在各自的控制器中实现啊  其中的两个tableview的点击 我已经在demo中实现了点击 你可以看一下

**Comment by DamonRao** [comment]
貌似不行啊，我试过了，其中绿色banner上面两行是可以的，但是banner下面的单元格本身不是该控制器表格的响应不了

**Comment by LeeWongSnail** [comment]
ArtSubTableViewController
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath

你那里不走这个方法吗？

**Comment by DamonRao** [comment]
是在这个方法里设置啊，点击后并没有跳转，你那里可以跳转？？？

**Comment by LeeWongSnail** [comment]
你是说不能响应还是无法跳转

**Comment by LeeWongSnail** [comment]
@DamonRao  是的 的确有这个问题 是navigationcontroller的问题 需要传递一下 我已经更新了demo 你参考一下 主要是传递了导航控制器

**Comment by DamonRao** [comment]
好的，我看下

**Comment by DamonRao** [comment]
楼主，我又有疑问，就是在向上滑动的的时候，自控制器内容如果是多组数据的表格，滑动的时候会连带着有层叠效果，手滑动体验不是很好，你可以试一下加个分组数据表格

**Comment by LeeWongSnail** [comment]
@DamonRao  您是想有那种效果呢？

**Comment by lihongyang108** [comment]
我看你这个耦合性太强了  能不能解下耦呢 能方便定制些

**Comment by LeeWongSnail** [comment]
> 我看你这个耦合性太强了 能不能解下耦呢 能方便定制些

其实只需要参考 对于scrollview的监听 以及手势的管理这两个地方就完全可以实现这个功能了

因为代码都是从项目里扒出来的 所以部分代码耦合度较高 见谅！！
