### ISSUE TITLE
楼主，有个严重的bug啊

### ISSUE THREAD

**Issue by DamonRao** [LeeWongSnail/ArtScrollTableView#2]
[self.workFilterModel setContentViewController:^UIViewController *(NSDictionary *info) {
       
        if ([info[@"_id"] isEqualToString:@"1"]) {
            
            LJNewsViewController *vc1=[[LJNewsViewController alloc]init];
            vc1.symbol=weakSelf.symbol;
            vc1.navigationController=weakSelf.navigationController;
          
             return  vc1;
            
        }
        
      else if([info[@"_id"] isEqualToString:@"2"]){
          
          LJFinanceViewController *vc2=[[LJFinanceViewController alloc]init];
          
          vc2.navigationController=weakSelf.navigationController;
          
          return vc2;
          
        }
       else{
           LJCATViewController *vc3=[[LJCATViewController alloc]init];
           vc3.navigationController=weakSelf.navigationController;
           return vc3;
       }
    }];
    
这一段，只有第一次加载的时候，才会走vc1,我返回上一界面后再次进来就不会到这个界面来了。如，我的vc1.symbol如果值有变化就没办法传递了

**Comment by LeeWongSnail** [comment]
这个可能跟控制器没有dealloc有关系吧，这个问题我这几天会尝试修复一下！ 多谢反馈！

**Comment by DamonRao** [comment]
楼主处理了没啊
